{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "dkonsole.fullname" . }}
  labels:
    {{- include "dkonsole.labels" . | nindent 4 }}
rules:
{{- range .Values.rbac.clusterResources }}
- apiGroups: {{ .apiGroups | toYaml | nindent 4 }}
  resources: {{ .resources | toYaml | nindent 4 }}
  verbs: {{ .verbs | toYaml | nindent 4 }}
{{- end }}
{{- range .Values.rbac.namespacedResources }}
- apiGroups: {{ .apiGroups | toYaml | nindent 4 }}
  resources: {{ .resources | toYaml | nindent 4 }}
  verbs: {{ .verbs | toYaml | nindent 4 }}
{{- end }}
{{- if .Values.rbac.nonResourceURLs }}
- nonResourceURLs: {{ .Values.rbac.nonResourceURLs | toYaml | nindent 4 }}
  verbs: ["get", "list", "watch"]
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "dkonsole.fullname" . }}
  labels:
    {{- include "dkonsole.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "dkonsole.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "dkonsole.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
