apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dkonsole.fullname" . }}-auth
  labels:
    {{- include "dkonsole.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-username: {{ .Values.admin.username | quote }}
  admin-password-hash: {{ .Values.admin.passwordHash | default "" | quote }}
  jwt-secret: {{ .Values.jwtSecret | default (randAlphaNum 32) | quote }}
