{{- if (dig "authSecret" "create" false .Values) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dkonsole.fullname" . }}-auth
  labels:
    {{- include "dkonsole.labels" . | nindent 4 }}
type: Opaque
data:
  # Optional placeholder secret (empty). Values will be populated by the application setup.
{{- end }}
