apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dkonsole.fullname" . }}-auth
  labels:
    {{- include "dkonsole.labels" . | nindent 4 }}
type: Opaque
data:
  # Initial empty secret to allow volume mount.
  # Values will be populated by the application setup.
